apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: backend-tests-python-lghjfofh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend-tests-python-lghjfofh 
  name: backend-tests-python-lghjfofh
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: backend-tests-python-lghjfofh 
